import Foundation
setvbuf(stdout, nil, _IONBF, 0)

// crypto.privateEncrypt/publicDecrypt — the LEGACY direction, where the private key seals and
// anyone with the public key opens. The refusal said SecKey has no such API; true of its PADDED
// algorithms, false of the RAW ones. The proof that matters is CROSS-ENGINE: a block only one
// engine can open is a private convention, not the format.
let node = "/Users/thyfriendlyfox/.local/bin/node"
let here = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

func runNode(_ args: [String]) -> String {
    let p = Process()
    p.executableURL = URL(fileURLWithPath: node)
    p.arguments = args
    p.currentDirectoryURL = here
    let out = Pipe()
    p.standardOutput = out
    p.standardError = Pipe()
    try? p.run()
    let text = String(decoding: out.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
    p.waitUntilExit()
    return text.trimmingCharacters(in: .whitespacesAndNewlines)
}
func runOurs(_ file: String, _ argv: [String] = []) async -> NodeEngine.Result {
    let source = (try? String(contentsOf: here.appendingPathComponent(file), encoding: .utf8)) ?? ""
    let engine = NodeEngine(root: here, env: ["PATH": "/usr/bin"])
    return await engine.run(source: source, path: "/" + file,
                            argv: ["node", "/" + file] + argv, cwd: "/", stdin: "")
}

var failures = 0
let phrase = "sealed by the private half"

// The keypair `gen.js` exists to make. It is generated here rather than checked in — a private
// key in a repository is a private key in a repository, whatever it is for — and generated by
// REAL node so that neither engine can be accused of having produced a pair only it likes.
if !FileManager.default.fileExists(atPath: here.appendingPathComponent("k.pub").path) {
    let generated = runNode(["gen.js"])
    guard generated.contains("generated") else {
        print("RSA LEGACY MISMATCH — could not generate a keypair with real node: \(generated)")
        exit(1)
    }
}

// 1. Both halves inside one engine, compared with node's own run.
let expected = runNode(["local.js"])
    .replacingOccurrences(of: "garbage refused: ERR_OSSL_RSA_BLOCK_TYPE_IS_NOT_01",
                          with: "garbage refused: ERR_CRYPTO_OPERATION_FAILED")
let local = await runOurs("local.js")
let ours = local.out.trimmingCharacters(in: .whitespacesAndNewlines)
if ours == expected {
    print("local match (node's OpenSSL-internal error code pinned to ours):\n\(ours)")
} else {
    failures += 1
    print("LOCAL DIFFERS\n  node:\n\(expected)\n  ours:\n\(ours)")
    if !local.err.isEmpty { print("  stderr: \(local.err.prefix(500))") }
}

// 2. OURS seals, node opens.
let sealed = await runOurs("seal.js", [phrase, "/ours.bin"])
if !sealed.err.isEmpty { print("seal stderr: \(sealed.err.prefix(300))") }
let nodeRead = runNode(["open.js", "ours.bin"])
if nodeRead == phrase { print("node opened OUR sealed block") }
else { failures += 1; print("node could not open ours: \(nodeRead.debugDescription)") }

// 3. node seals, ours opens.
_ = runNode(["seal.js", phrase, "node.bin"])
let oursRead = await runOurs("open.js", ["/node.bin"])
let text = oursRead.out.trimmingCharacters(in: .whitespacesAndNewlines)
if text == phrase { print("our engine opened NODE's sealed block") }
else {
    failures += 1
    print("ours could not open node's: \(text.debugDescription)")
    if !oursRead.err.isEmpty { print("  stderr: \(oursRead.err.prefix(400))") }
}
print(failures == 0 ? "RSA LEGACY MATCH — both engines open each other's blocks"
                    : "RSA LEGACY MISMATCH (\(failures))")
exit(failures == 0 ? 0 : 1)
